# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "d4f5f556a9fb0bdca8da5e52f752b7fba6bedce5";
      sha256 = "0a7sdkf085njyk48aia9mv1wmns89k8rg2flz9bqljrraaildlza";
    };
  }
  {
    goPackagePath = "github.com/jmespath/go-jmespath";
    fetch = {
      type = "git";
      url = "https://github.com/jmespath/go-jmespath";
      rev = "b0104c826a24d7c202da8e1dbfb9ea4cfa35d774";
      sha256 = "154z58r7m7iq7yv4z751h8vgvrdm0d5yf9lxxysqgqzhdwpi9spd";
    };
  }
]
